cache:
  paths:
    - .yarn/

stages:
  - prepare
  - test
  - build
  - review
  - deliver
  - release


# Workflow rules for MR-Pipelines taken from docs at docs.gitlab.com:
# https://docs.gitlab.com/ee/ci/yaml/#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

lint code:
  stage: prepare
  before_script:
    - yarn install --cache .yarn --prefer-offline
  script:
    - yarn lerna run lint
  rules:
    - changes:
        - packages/*
      when: always

include:
  - local: packages/conversion-service/.gitlab-ci.yml
  - local: packages/auto-scaler/.gitlab-ci.yml
  - local: packages/redis/.gitlab-ci.yml
