cache:
  paths:
    - .yarn/

stages:
  - prepare
  - test
  - build
  - review
  - deliver
  - release

include:
  - local: packages/conversion-service/.gitlab-ci.yml
  - local: packages/auto-scaler/.gitlab-ci.yml