version: "3"
services:
  redis-server:
    image: redis:6.2.5-alpine
  redis-conversion-manager:
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file: ./template.env
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
