.logger-before-script: &logger-before-script
  before_script:
    - cd packages/logger
    - yarn install --cache .yarn --prefer-offline

typecheck logger:
  stage: "test:types"
  <<: *logger-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - packages/logger/**/*.ts

test unit logger:
  stage: "test:unit"
  needs:
    - job: "typecheck logger"
  <<: *logger-before-script
  script:
    - |
      yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  rules:
    - changes:
        - packages/logger/**/*.ts
      when: always
