process.env.WEBSERVICE_PORT = "3000"
process.env.FFMPEG_PATH = "/usr/bin/ffmpeg"
process.env.IMAGE_MAGICK_PATH = "usr/bin/convert"
process.env.UNOCONV_PATH = "/usr/bin/unoconv"
process.env.MAX_CONVERSION_TIME = "90000"
process.env.MAX_CONVERSION_TRIES = "1"
process.env.CONVERTER_DOCUMENT_PRIORITY = "unoconv,imageMagick"
process.env.CONVERTER_MEDIA_PRIORITY = "ffmpeg,imageMagick,unoconv"
import { Api } from "./service/api"
new Api()