/* Tslint:disable */
/* eslint-disable */
/**
 * conversion-service
 * A webservice with a REST Api which can convert document/media files using different binaries
 *
 * The version of the OpenAPI document: 0.1.13-2
 * Contact: sven.patrick.meier@team-parallax.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

