.auto-scaler-before-script: &auto-scaler-before-script
  before_script:
    - cd packages/auto-scaler
    - yarn install --cache .yarn --prefer-offline

typecheck auto-scaler:
  stage: "test:types"
  <<: *auto-scaler-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - packages/auto-scaler/**/*.ts
      when: always

test unit auto-scaler:
  stage: "test:unit"
  needs:
    - job: "typecheck auto-scaler"
  <<: *auto-scaler-before-script
  variables:
    IS_CI: 1
  script:
    - yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  allow_failure: true
  rules:
    - changes:
        - packages/auto-scaler/**/*.ts
      when: always
