default:
  interruptible: true

stages:
  - prepare
  - test

# Workflow rules for MR-Pipelines taken from docs at docs.gitlab.com:
# https://docs.gitlab.com/ee/ci/yaml/#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

.auto-scaler-before-script: &auto-scaler-before-script
  before_script:
    - cd packages/auto-scaler
    - yarn install --cache .yarn --prefer-offline

typecheck auto-scaler:
  stage: prepare
  <<: *auto-scaler-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - packages/auto-scaler/*