.redis-before-script: &redis-before-script
  before_script:
    - cd packages/redis
    - yarn install --cache .yarn --prefer-offline

typecheck redis:
  stage: "test:types"
  <<: *redis-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - packages/redis/**/*.ts

test unit redis:
  stage: "test:unit"
  services:
    - redis:6.2.5-alpine
  needs:
    - job: "typecheck redis"
  <<: *redis-before-script
  script:
    - |
      yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  rules:
    - changes:
      - packages/redis/**/*.ts

test integration redis:
  extends: "test unit redis"
  services:
  - redis:6.2.5-alpine
  stage: "test:integration"
  needs:
    - job: "test unit redis"
  script:
    - yarn test:integration:coverage --ci
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/integration/junit.xml
    reports:
      junit: artifacts/test/integration/junit.xml
  rules:
    - changes:
      - packages/redis/**/*.ts