version: "3"
services:
  dynamic-conversion-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file: ./template.env
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
