default:
  image: teamparallax/conversion-service-base-image:v0.2.2
  interruptible: true

cache:
  paths:
    - .yarn/

stages:
  - prepare
  - test
  - build
  - review
  - deliver
  - release

# Workflow rules for MR-Pipelines taken from docs at docs.gitlab.com:
# https://docs.gitlab.com/ee/ci/yaml/#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

.conversion-service-before-script: &conversion-service-before-script
  before_script:
    - cd packages/conversion-service
    - yarn install --cache .yarn --prefer-offline

typecheck conversion-service:
  stage: prepare
  <<: *conversion-service-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - src/**/*.ts
      when: always
    - changes:
      - packages/conversion-service/*

build docker:
  stage: build
  needs:
    - job: "test unit conversion-service"
    - job: "test unit auto-scaler"
    - job: "test unit redis"
    - job: "test integration conversion-service"
  services:
    - docker:19.03.5-dind
  before_script:
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
    - cd packages/conversion-service
  image: docker:19.03.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    DOCKER_USER: ${DOCKER_USER}
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: docker.io
  script:
    - docker build -t ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG} -f ./Dockerfile .
    - docker push ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG}
    - docker build -t ${IMAGE_BASE_NAME}:latest -f ./Dockerfile .
    - docker push ${IMAGE_BASE_NAME}:latest
  rules:
    - if: $CI_COMMIT_TAG

test unit conversion-service:
  stage: test
  needs: 
  - job: "typecheck conversion-service"
  <<: *conversion-service-before-script
  script:
    - |
      mkdir -p ./output/ ./input/
      yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  rules:
    - changes:
      - packages/conversion-service/*
    - changes:
        - src/**/*.ts
      when: always

test integration conversion-service:
  extends: "test unit conversion-service"
  needs:
    - job: "typecheck conversion-service"
  script:
    - yarn test:integration --ci
  artifacts:
    paths:
      - artifacts/test/integration/junit.xml
    reports:
      junit: artifacts/test/integration/junit.xml
  retry: 2
  rules:
    - changes:
      - packages/conversion-service/*


