default:
  image: teamparallax/conversion-service-base-image:v0.1.0

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .npm/

stages:
  - lint
  - test
  - build

# Workflow rules for MR-Pipelines taken from gitlab.com
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG


before_script:
  - yarn install --cache .npm --prefer-offline

build_docker:
  stage: build
  services:
    - docker:19.03.5-dind
  before_script: []
  image: docker:19.03.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    DOCKER_USER: ${DOCKER_USER}
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: docker.io
  script:
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
    - docker build -t ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG} -f ./Dockerfile .
    - docker push ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG

lint_code:
  stage: lint
  script:
    - yarn lint


test_all:
  stage: test
  script:
    - yarn test:all:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    expire_in: 30 days
    untracked: false
    reports:
      junit: junit.xml
