default:
  image: teamparallax/conversion-service-base-image:v0.2.2
  interruptible: true

cache:
  paths:
    - .yarn/

stages:
  - prepare
  - test
  - build
  - review
  - deliver
  - release

# Workflow rules for MR-Pipelines taken from docs at docs.gitlab.com:
# https://docs.gitlab.com/ee/ci/yaml/#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG

.conversion-service-before-script: &conversion-service-before-script
  before_script:
    - cd packages/conversion-service
    - yarn install --cache .yarn --prefer-offline

typecheck conversion-service:
  stage: prepare
  <<: *conversion-service-before-script
  script:
    - yarn test:types
  rules:
    - changes:
        - src/**/*.ts
      when: always
    - changes:
      - packages/conversion-service/*

build docker:
  stage: build
  needs:
    - job: "test unit conversion-service"
    - job: "test integration"
  services:
    - docker:19.03.5-dind
  before_script:
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
  image: docker:19.03.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    DOCKER_USER: ${DOCKER_USER}
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: docker.io
  script:
    - docker build -t ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG} -f ./Dockerfile .
    - docker push ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG}
    - docker build -t ${IMAGE_BASE_NAME}:latest -f ./Dockerfile .
    - docker push ${IMAGE_BASE_NAME}:latest
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - packages/conversion-service/*

test unit conversion-service:
  stage: test
  <<: *conversion-service-before-script
  script:
    - |
      mkdir -p ./output/ ./input/
      yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  rules:
    - changes:
      - packages/conversion-service/*
    - changes:
        - src/**/*.ts
      when: always

test integration:
  extends: "test unit conversion-service"
  script:
    - yarn test:integration --ci
  artifacts:
    paths:
      - artifacts/test/integration/junit.xml
    reports:
      junit: artifacts/test/integration/junit.xml
  rules:
    - changes:
      - packages/conversion-service/*

code quality:
  allow_failure: true
  image: docker:stable
  services:
    - docker:stable-dind
  stage: review
  needs:
    - job: "lint code"
    - job: "typecheck conversion-service"
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
    REPORT_FORMAT: json
    SOURCE_CODE: ${PWD}/src/
  before_script: []
  script:
    - echo "Generate Gitlab Code Quality Report"
    - |
      docker run \
        --env SOURCE_CODE="${PWD}" \
        --volume "${PWD}":/code \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:0.85.24" /code
  artifacts:
    paths:
      - gl-code-quality-report.json
    reports:
      codequality: gl-code-quality-report.json
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - changes:
        - src/**/*.ts
      when: always

# The steps below originally come from here, but the release_job step
# should wait for the docker build before creating a release
# https://gitlab.com/uulmhack/pipelines/auto-create-release/-/blob/master/.gitlab-ci.yml
prepare release:
  image: alpine:3.13
  stage: prepare
  before_script:
    - apk add --no-cache git
  script:
    - |
      echo "Generate diff from last release for the latest release"
      git diff --unified=0 HEAD~1 ./CHANGELOG.md | tail -n +6 | sed -e "s/^+//" > ./latestChanges.md
  artifacts:
    paths:
      - ./latestChanges.md
  rules:
    - if: '$CI_COMMIT_TAG'
      exists:
        - CHANGELOG.md

release job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script: []
  needs:
    - job: "build docker"
    - job: "prepare release"
      artifacts: true
    - job: "code quality"
    - job: "test unit conversion-service"
    - job: "test integration"
    - job: "docker latest tag"
  script:
    - echo "create gitlab-release for ${CI_COMMIT_TAG}"
  stage: release
  release:
    tag_name: $CI_COMMIT_TAG
    description: "./latestChanges.md"
  rules:
    - if: $CI_COMMIT_TAG
