.conversion-service-before-script: &conversion-service-before-script
  before_script:
    - cd packages/conversion-service
    - yarn install --cache .yarn --prefer-offline

typecheck conversion-service:
  stage: "test:types"
  image: teamparallax/conversion-service-base-image:v0.2.2
  <<: *conversion-service-before-script
  script:
    - yarn test:types
  rules:
    - changes:
      - packages/conversion-service/**/*.ts

test unit conversion-service:
  stage: "test:unit"
  image: teamparallax/conversion-service-base-image:v0.2.2
  needs:
  - job: "typecheck conversion-service"
  <<: *conversion-service-before-script
  script:
    - |
      mkdir -p ./output/ ./input/
      yarn test:unit:coverage --ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 7 days
    paths:
      - artifacts/test/unit/junit.xml
    reports:
      junit: artifacts/test/unit/junit.xml
    untracked: false
    when: always
  rules:
    - changes:
        - packages/conversion-service/**/*.ts
      when: always

test integration conversion-service:
  extends: "test unit conversion-service"
  stage: "test:integration"
  needs:
    - job: "test unit conversion-service"
  script:
    - yarn test:integration:coverage --ci
  artifacts:
    paths:
      - artifacts/test/integration/junit.xml
    reports:
      junit: artifacts/test/integration/junit.xml
  retry: 2
  rules:
    - changes:
        - packages/conversion-service/**/*.ts
      when: always
