variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  DOCKER_USER: ${DOCKER_USER}
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: docker.io

build docker dynamic-conversion-controller:
  stage: build
  image: docker:19.03.5-dind
  services:
    - docker:19.03.5-dind
  needs:
    - job: "test integration conversion-service"
    - job: "test integration redis"
  before_script:
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
  script:
    - |
      docker build -t teamparallax/dynamic-conversion-controller:${CI_COMMIT_TAG} \
        -t teamparallax/dynamic-conversion-controller:latest \
        -f ./Dockerfile .
      docker push ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG}
      docker push ${IMAGE_BASE_NAME}:latest
  rules:
    - if: $CI_COMMIT_TAG

build docker conversion-service:
  stage: build
  image: docker:19.03.5-dind
  services:
    - docker:19.03.5-dind
  needs:
    - job: "test integration conversion-service"
  before_script:
    - echo -n "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USER} --password-stdin ${REGISTRY}
    - cd packages/conversion-service
  script:
    - |
      docker build -t ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG} \
        -t ${IMAGE_BASE_NAME}:latest \
        -f ./Dockerfile .
      docker push ${IMAGE_BASE_NAME}:${CI_COMMIT_TAG}
      docker push ${IMAGE_BASE_NAME}:latest
  rules:
    - if: $CI_COMMIT_TAG